### ISSUE TITLE
images missing

### ISSUE THREAD

**Issue by jodevelops** [exc-asia-and-europe/ziziphus#260]
images are missing in ziziphus 0.40 (they are not loaded into Z.)

Also, thumbnails of related images are missing

**Comment by zwobit** [comment]
Where? User-Collections? PPCOL seems to work.

**Comment by jodevelops** [comment]
on ws2, i cannot see the images in Z., not in PPColl, nor in my own collections

**Comment by MatthiasArnold** [comment]
problem confirmed: images show in z on live server (v0.35), but not on test server (v0.40). 
tested on these collections (test server):
* public:
  * /data/commons/Samples/Priya_Paul_Sample_Records
  * /data/commons/Priya_Paul_Collection
  * /data/commons/Ethnografische_Fotografie
* shared:
  * /data/users/johannes.alisch@ad.uni-heidelberg.de/Jos Records
  * /data/users/editor/Bani
* private:
  * /data/users/marnold1@ad.uni-heidelberg.de/Matzes images

**Comment by zwobit** [comment]
Ah, it only happens if you call Z from T.

**Comment by zwobit** [comment]
Should be fixed on ws2 an in T trunk.

**Comment by jodevelops** [comment]
reopened: 
related images (thumbnails) in relationSet are still missing, Image & Work record

**Comment by MatthiasArnold** [comment]
confirmed: thumbs in relationSet (work AND image) still missing
![image](https://cloud.githubusercontent.com/assets/3436613/6245118/56ddcac6-b75b-11e4-8e8b-0fd8e55fd919.png)

**Comment by SimonGruening** [comment]
Related but closed issue was #216

**Comment by MatthiasArnold** [comment]
HALF of the problem is solved: in v0.41 thumbnails appear in WORK relation. :)
however, the links are still broken in IMAGE relation. this is the case in both, personal collections (e.g. "matzes images"), and commons collections (e.g. "Priya_Paul_Collection").

Example (ppcoll):
![28-05-2015 17-28-25](https://cloud.githubusercontent.com/assets/3436613/7863895/325c67a0-055f-11e5-9ec2-da65739cd78a.png)

**Comment by zwobit** [comment]
Right now i am not 100% sure what we should show for the imagerecord. Right now i show the "pref" (if present) image record from the work record or the first one.  Is this okay?

**Comment by jodevelops** [comment]
yes, sounds very plausible to me. And when 1.) the first entry in relationSet is NOT an image record ("imageIs") and 2.) when there is NO pref=true setting on any related image (type "imageIs") the entries have to be skipped until there is one that fits the conditions.

**Comment by jodevelops** [comment]
all fine in WORK record.

Did we want an image thumbnail in the "relationSet" of the image record as well?

**Comment by zwobit** [comment]
ImageRecord related image type =  "imageOf"

**Comment by zwobit** [comment]
done. If relid is a imagerecord id this is used, if it is a workrecord id first pref + ImageIs or first ImagesIs is used
